name: travel_wisata_lokal
description: Aplikasi Travel Wisata Lokal
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8
  path: ^1.8.3
  path_provider: ^2.0.15
  image_picker: ^0.8.7+5
  google_maps_flutter: ^2.2.5
  google_fonts: ^6.2.1
  url_launcher: ^6.2.5
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#4CAF50"  # Hijau sesuai tema alam
  image: assets/images/icon.png
  android: true
  ios: true
